# Generated by Django 5.1.1 on 2024-10-03 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmpID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Title', models.CharField(max_length=100)),
                ('PhoneNo', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('MachineName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('ShiftName', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('StartTime', models.TimeField()),
                ('EndTime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductionReport',
            fields=[
                ('ReportID', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('PartName_1', models.CharField(max_length=100)),
                ('MaterialName_1', models.CharField(max_length=100)),
                ('MaterialGrade_1', models.CharField(max_length=100)),
                ('RM_LotNo_1', models.CharField(max_length=100)),
                ('Std_CT_1', models.IntegerField()),
                ('Act_CT_1', models.IntegerField()),
                ('Std_Wt_1', models.IntegerField()),
                ('PartName_2', models.CharField(blank=True, max_length=100, null=True)),
                ('MaterialName_2', models.CharField(blank=True, max_length=100, null=True)),
                ('MaterialGrade_2', models.CharField(blank=True, max_length=100, null=True)),
                ('RM_LotNo_2', models.CharField(blank=True, max_length=100, null=True)),
                ('Std_CT_2', models.IntegerField(blank=True, null=True)),
                ('Act_CT_2', models.IntegerField(blank=True, null=True)),
                ('Std_Wt_2', models.IntegerField(blank=True, null=True)),
                ('MachineName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.machine')),
                ('Operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.employee')),
                ('ShiftName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.shift')),
            ],
        ),
        migrations.CreateModel(
            name='HourlyProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.CharField(choices=[('07:00-08:00', '07:00-08:00'), ('08:00-09:00', '08:00-09:00'), ('09:00-10:00', '09:00-10:00'), ('10:00-11:00', '10:00-11:00'), ('11:00-12:00', '11:00-12:00'), ('12:00-13:00', '12:00-13:00'), ('13:00-14:00', '13:00-14:00'), ('14:00-15:00', '14:00-15:00'), ('15:00-16:00', '15:00-16:00'), ('16:00-17:00', '16:00-17:00'), ('17:00-18:00', '17:00-18:00'), ('18:00-19:00', '18:00-19:00')], default='07:00-08:00', max_length=20)),
                ('count', models.IntegerField()),
                ('total', models.IntegerField()),
                ('ok', models.IntegerField()),
                ('rejection', models.IntegerField()),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('downtime', models.FloatField(blank=True, null=True)),
                ('dt_remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.productionreport')),
            ],
        ),
        migrations.CreateModel(
            name='ScrapAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejection_quantity', models.IntegerField()),
                ('runner_weight', models.FloatField()),
                ('lumps', models.FloatField()),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.productionreport')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.shift')),
            ],
        ),
        migrations.CreateModel(
            name='InjectionMolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_weight', models.FloatField()),
                ('standard_count', models.IntegerField()),
                ('start_count', models.IntegerField()),
                ('end_count', models.IntegerField()),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.productionreport')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.shift')),
            ],
        ),
    ]
